### ISSUE TITLE
Clicking "Virtual x86" application fails

### ISSUE THREAD

**Issue by ajmeese7** [DustinBrett/daedalOS#190]
Hey Dustin, this is similar to the problem I raised in #53, in that the default opening of the "Virtual x86" application could benefit by having a different behavior.

Whenever I open the application directly instead of running the *Linux* or *Kolibri* disk image, this is what I am greeted with:

```text
SeaBIOS (version rel-1.12.1-0-ga5cab58)
Booting from Floppy...
Boot failed: could not read the boot disk

Booting from Hard Disk...
Boot failed: could not read the boot disk

No bootable device.  Retrying in 60 seconds.
```

In my opinion, this would be best if it defaults to something else, such as opening the *Linux* image if no other image is specified. That or maybe displaying a GUI listing the available disk images as well as a DnD box to upload additional disk images if desired, for the less technically-savvy site visitor.

**Comment by DustinBrett** [comment]
Thanks for the feedback.

In this case I actually like it booting into this because it emulates the behavior of a computer being turned on with no disk setup. Unlike the Markdown example where it was a blank white screen, at least with v86 it shows the user something. An iso can be dragged onto that screen to have it load an image.

I agree its not totally clear, but also that is part of the fun a bit.

**Comment by ajmeese7** [comment]
Gotcha, thanks for the quick response!
