### ISSUE TITLE
V86 unable to be resized

### ISSUE THREAD

**Issue by ajmeese7** [DustinBrett/daedalOS#192]
The "Virtual x86" application is currently unable to be resized, regardless of whether there is an image loaded or not. Unsure if this is by design or unintentional, so I wanted to mention it in case you were not aware.

**Comment by DustinBrett** [comment]
Thanks. It is indeed by design because of lack of resizing after the fact within v86. I think it would not be trivial to have resize work in a good way when its running a linux gui. Several apps cant be resized that rely on canvas and have non-ideal api's for dynamically changing their sizes. If you can find a way to do it with v86 I'd be happy to integrate it, but I dont think its easy. Same issue with a few apps that have hardcoded libs for doing some of the pointer event listeners which makes scaling also not work. Its just one of the limits I have accepted as I use various 3rd party scripts with different levels of flexibility.
