### ISSUE TITLE
Thumbnails in folder preview displayed incorrect

### ISSUE THREAD

**Issue by SuperMaxusa** [DustinBrett/daedalOS#271]
Thumbnails in folder preview (File Explorer) shows incorrectly, i.e. as if rotated 90 degrees.

![2](https://user-images.githubusercontent.com/41739128/219396397-ab254d28-613a-489f-af68-3ae66e9bc18c.png)

**Comment by DustinBrett** [comment]
Just to clarify, what about it looks wrong to you? The fact it's side ways or is there more?

I'd actually shifted it on purpose, but at the moment I can't find the example in Windows 10 I followed where this made sense. I will do more testing on this and if I can't recreate the sideways groupings I will make adjustments.

**Comment by SuperMaxusa** [comment]
@DustinBrett Oops, sorry, I forgot more details.

I mean the thumbnails in folder preview (File Explorer) shows incorrectly, i.e. as if rotated 90 degrees.

I made an example of how the [same image](https://user-images.githubusercontent.com/41739128/219581280-88ca7203-bba0-484e-9525-9aaa5e27932e.png) is displayed in daedalOS and Windows 10. 


### daedalOS (left) and Windows 10 (right):
![example](https://user-images.githubusercontent.com/41739128/219577618-311e514e-4852-4a4c-94d8-b9254fd1d1e8.png)

### If compare only images:
![example2](https://user-images.githubusercontent.com/41739128/219583918-4310c733-0d74-49f1-8455-9b8de303bb5e.png)

### And other example:
![example](https://user-images.githubusercontent.com/41739128/219586708-1200e90c-33f3-4e8d-938a-3ba338b281f7.png)

**Comment by DustinBrett** [comment]
So it looks like maybe my image had rotated when I was making this feature because of the EXIF orientation flag being set. But in general it seems the images should not rotate, so I've changes the `transform: matrix()` values. In addition to changing this I have done finer tweaking to the positioning of the icons (https://github.com/DustinBrett/daedalOS/commit/c91b02d0267844a8e8a4860a9f49e7bfa2e92b9b & https://github.com/DustinBrett/daedalOS/commit/ed95f41df621694cada07ce64558297d1f13d3dd). I've also changed the code that generates the thumbnails so that it accounts for natural dimensions (https://github.com/DustinBrett/daedalOS/commit/2437b5a465063d2b6dff655153e24af07b3a3dd8) and removes the transparency, which allows me to fix sizing issues I was having that `object-fit` couldn't folder when the images intrinsic dimensions were no longer known.

I will be updating this code on my live site shortly after fixing a few other bugs I've introduced. I will leave this open until I publish the code and make new screenshots.

**Comment by DustinBrett** [comment]
Here are some examples of the fix. I will close this as resolved until I can think of further tweaks. Feel free to comment or reopen if I missed something.

Test Image: 
![image](https://user-images.githubusercontent.com/16656318/219923334-9ed58a7b-4cfe-4e89-b150-0bbbd6faf20e.png)

daedalOS: 
![image](https://user-images.githubusercontent.com/16656318/219923321-cb424d4b-ba6f-4f01-ba64-30d31f91cbbb.png)

Windows 10: 
![image](https://user-images.githubusercontent.com/16656318/219923331-ef163bf5-004c-4ad4-b925-cc9ed7eb0f7b.png)

Games Folder: 
![image](https://user-images.githubusercontent.com/16656318/219923343-bdbafc06-cb85-471d-855a-d77b7c7cb840.png)

Travel Folder: 
![image](https://user-images.githubusercontent.com/16656318/219923366-b0b7de3b-1253-4aaf-930e-83bc8ee1bd4a.png)
