### ISSUE TITLE
Question: how to track tweaks to BrowserFS

### ISSUE THREAD

**Issue by kumavis** [DustinBrett/daedalOS#299]
since only the built file is commited to the repo, its hard track the changes

**Comment by DustinBrett** [comment]
Yes it is true it's harder to track. I had forked the repo and was working on some branches but there have been a lot of changes recently by other devs on that repo and rather than keep upstream I just had my own local copy. I can attach a diff here for reference. Long term I may update my forked repo rather than include those sources in this repo. But as it's changing I would rather update it before adding to the fork.

[bfs changes.patch](https://github.com/DustinBrett/daedalOS/files/11400935/bfs.changes.patch)
