### ISSUE TITLE
Can only have one anonymous define call per script file

### ISSUE THREAD

**Issue by ajboni** [DustinBrett/daedalOS#34]
Hope it helps: 
1. Opened Monaco editor, fiddled around with a json file. 
2. Closed Editor.
3. No program will launch

```
Uncaught (in promise) Error: Can only have one anonymous define call per script file
    at s.enqueueDefineAnonymousModule (/Program%20Files/MonacoEditor/vs/loader.js:8)
    at _ (/Program%20Files/MonacoEditor/vs/loader.js:9)
    at eval (eval at <anonymous> (/Program%20Files/js-dos/js-dos.js:1), <anonymous>:3:1)
    at eval (<anonymous>)
    at /Program%20Files/js-dos/js-dos.js:1
    at f (/Program%20Files/js-dos/js-dos.js:1)
    at Generator.c._invoke (/Program%20Files/js-dos/js-dos.js:1)
    at Generator.e.<computed> [as next] (/Program%20Files/js-dos/js-dos.js:1)
    at u (/Program%20Files/js-dos/js-dos.js:1)
    at o (/Program%20Files/js-dos/js-dos.js:1)
```
![image](https://user-images.githubusercontent.com/12578313/148709978-6a26b5ac-e3a4-4e63-b9af-b46e13147cce.png)

**Comment by DustinBrett** [comment]
Thanks for the bug report. There is indeed some issues around `window.define` and Monaco. I am still trying to find the best way to resolve it. I will keep this issue updated if I ever solve it. I need Monaco to be able to set `window.define` while also allowing other libraries to set/use it.

**Comment by DustinBrett** [comment]
If anyone has an idea how to setup proxy with `window.define` and Monaco, I'd be very interested. I've tried [Reflect](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect) & [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) but the issue I run into is that Monaco seems to actually check that `window.define` is exactly the function it expects, and it is modified to be a an in-between, so I have not yet figured out a way around this, instead of try and manage access to `window.define`, but several other apps also use it and when Monaco breaks it, issues occur.

**Comment by DustinBrett** [comment]
This seems to not be happening atm with React 18. If it can be recreated please reopen.
